CONST = 0
BLK_ST = 1
BLK_TOT = 2
RELEASE = 3
PERIOD = 4
EXEC = 5
DEADLINE = 6
PLUS = 7
MINUS = 8
TIMES = 9
DIVIDED_BY = 10
MOD = 11
MAX = 12
MIN = 13
CURRENT_TIME = 14
J_DEADLINE = 15
J_RELEASE = 16
# NUM_OPERATIONS = 15

OPERATORS = [PLUS, MINUS, TIMES, DIVIDED_BY, MOD, MAX, MIN]
NONSTATIC = [CURRENT_TIME, J_DEADLINE, J_RELEASE]
LEAVES = [CONST, BLK_ST, BLK_TOT, RELEASE, PERIOD,
          DEADLINE, EXEC, CURRENT_TIME, J_DEADLINE, J_RELEASE]

OPSUM = OPERATORS + LEAVES
