CONST = 0
BLK_ST = 1
BLK_TOT = 2
OFFSET = 3
PERIOD = 4
EXEC = 5
DEADLINE = 6
PLUS = 7
MINUS = 8
TIMES = 9
DIVIDED_BY = 10
MOD = 11
MAX = 12
MIN = 13
CURRENT_TIME = 14
# NUM_OPERATIONS = 15

OPERATORS = [PLUS, MINUS, TIMES, DIVIDED_BY, MOD, MAX, MIN]
LEAVES = [CONST, BLK_ST, BLK_TOT, OFFSET, PERIOD, DEADLINE, EXEC, CURRENT_TIME]

OPSUM = OPERATORS + LEAVES
